# OpenML dev docker-compose
# For local dev environment setup
# *Insecure & Not for production use*

# Notes:
# Rui Quintino,https://github.com/rquintino
# config folder is used to share some config keys after init between containers
# $ needs escaping to $$ in docker_compose file, $api_key is then $$api_key
# TODO: gollum not working, CORS issue, needs apache mapping, local gollum install on website container?
# OpenML main repo is mapped as volume, not copied within the built images, for enable development
   
version: '3'

services:
  mysql:
    build: 
      context: ./
      dockerfile: ./mysql/Dockerfile
    #ports:
    #  - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: openml
      #MYSQL_RANDOM_ROOT_PASSWORD: "true"
      #MYSQL_DATABASE: openml_expdb

  elasticsearch:
    build: ./elasticsearch
      #context: ./
      #dockerfile: ./Dockerfile-elasticsearch
    command: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"

  website:
    build:
      context: ./
      dockerfile: ./website/Dockerfile
    ports:
      - 80:80
    volumes: 
      - ./config:/openmlconfig
      - ./openml:/var/www/html
    depends_on:
      - mysql
      - elasticsearch
      - gollum
  
  # MySQL admin UI (tool)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    volumes: 
      - ./config:/openmlconfig
    ports:
      - 8080:80
    environment:
      - PMA_HOST=mysql
      #- PMA_ARBITRARY=1
    depends_on:
      - mysql

  # OpenML Java background workers
  java:
    image: java
    volumes: 
      - ./config:/openmlconfig
      - ./openml:/var/www/html
    
    # runs openml process_dataset java background task each 10 secs
    command: /bin/bash -c 'while sleep 10;do api_key=`cat /openmlconfig/api_key.txt`; echo "API key:$$api_key";  java -Xmx4G -jar /var/www/html/openml_OS/third_party/OpenML/Java/evaluate.jar -config "server = http://website/;api_key = $$api_key" -f process_dataset;done'

  # OpenML Wiki, TODO: not working , CORS/cross domain issue
  gollum:
    build: ./gollum
    ports:
      - 9080:80
